# workflow name
name: project-01

#event >> trigger
on: ["push"]

jobs:
  # name
  test-job:
    # OS or Platform
    runs-on: ubuntu-latest
      # steps
      steps:
      -uses: actions/checkout@v4
      -uses: actions/setup-python@v5
      with:
      python-version: '3.10'
      -run: python3 ./scripts/hello.py